version: '3.7'
services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    restart: always
  pup-server:
    container_name: pup-server
    build:
      context: ./redis.pup/
    ports:
      - 7010:8080
  sub-server:
    container_name: sub-server
    build:
      context: ./redis.sub/.
    ports:
      - 7020:8080